# Generated by Django 5.2.7 on 2025-10-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstep',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
