# Generated by Django 5.2.7 on 2025-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0002_alter_learningstep_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstep',
            name='date',
            field=models.DateField(),
        ),
    ]
