# Generated by Django 5.2.7 on 2025-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0003_alter_learningstep_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstep',
            name='step_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
