# Generated by Django 5.2.7 on 2025-10-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0004_learningstep_step_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningstep',
            old_name='step_no',
            new_name='Step_no',
        ),
    ]
