# Generated by Django 5.2.7 on 2025-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0006_rename_step_no_learningstep_step_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.TextField(default='About Me description'),
            preserve_default=False,
        ),
    ]
