# Generated by Django 5.2.7 on 2025-10-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntJourney', '0007_aboutme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='bio',
        ),
    ]
